# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a51f463a4985caefef92963c79ed8f43e09bc8b0ffde8659e0c27e877f8c6927175b370fdacb6353d7c96d1419f6a771032013ceefbe5b4a7dec68675f55a069

test:
  secret_key_base: 4efe16b37b500c3afa48b8f7a01c9b7fa8b3cc89e2db902d1e25cb49536f86dacbb920bb861ef18b0c8272fedd83f5afa8d7c75ac4112724b7a29766b030b73a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
